name: Publish-CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm package, test and storybook generation
      run: |
        npm run package
        npm run test
        npm run storybook:build
    - uses: actions/upload-artifact@v2
      with:
        name: storybook-demo
        path: storybook-static/
      env:
        CI: true

  publish:

    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      - uses: actions/checkout@v1
      - name: Publish on artifactory
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm package, test and storybook generation
        run: |
          npm run package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

  deploy:

    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: storybook-demo
          path: demo-public
      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy on Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=demo-public
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
